### ISSUE TITLE
谷歌中国IP可用于代理很多谷歌服务，加速谷歌访问质量

### ISSUE THREAD

**Issue by shuangzhijinghua** [zxdrive/imouto.host#23]
lh_.googleusercontent.com/gmail/ggpht.com/地图/谷歌账户登陆域名/play/_.gstatic.com/短域名地址/ytimg.com/clients_.google.com/谷歌新闻，android.clients.google.com这个域名可能比较挑剔IP，_.googleapis.com部分不能用国内IP，搜索不能用国内IP，基本主页面域名站除了play之外不能用国内IP。测试方法:绑定域名之后直接https://访问，报404的基本可以没问题，报403就说明不行(这里讲的就是play.googleapis.com似乎怎样都是403)，这样才能算是加速谷歌访问。你的hosts里面的IP大多使用谷歌美国骨干网的IP，部分使用了谷歌台湾HINET的GGC，hinet基本都是很容易封的，还不如173.194.120.*。当然用vpngate找日本韩国的GGC质量一般也可以，延迟比较低。实在不行就用64.233的吧。youtube视频地址很多。。看YouTube视频的时候多记着点地址吧。。

**Comment by Banshee12** [comment]
我只關心能否翻牆回國看優酷視頻，這篇評論希望能幫到大家：http://www.bestvpnchina.net/%E4%B8%AD%E5%9B%BDvpn%E6%8E%A8%E8%8D%90/
